### PR TITLE
V2.3.0

### LINKED ISSUE #26: Convert to dotnet 6
- Convert to dotnet 6
- Update packages
- Update docs as needed

### PR DESCRIPTION
**Pull request by bartr**
# Purpose of PR

- Move to dotnet 6.0
- doc updates
- minor bug fix

## Type of PR

- [x] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Validation

- [x] Unit tests updated and ran successfully
- [x] Update documentation or issue referenced above

## Issues Closed

- Closes #26

### CODE REVIEW

**Review by aflinchb — APPROVED** [review]

**Review by sivamu — CHANGES_REQUESTED** [review]
Blocking for now to discuss whether to add setter method for:
https://github.com/microsoft/webvalidate/blob/main/src/app/WebValidation/Model/Request.cs#L47

**Comment by bartr** [comment]
@sivamu  we don't need a setter method as it's a collection so you can clear / add / remove / update the individual headers

**Review by sivamu — APPROVED** [review]

**Review by hattan — APPROVED** [review]
LGTM

**Comment by bartr** [comment]
@sivamu because we deserialize json into the request object, we need a set. I added the set and a comment. Headers are now working.

**Pull request merged**
